services:
  webapp:
    container_name: webapp-dev
    image: ft_transcendence:dev
    build:
      context: .
      dockerfile: Dockerfile
      target: development-dependencies-env
    command: bun dev -- --host --port 5173
    depends_on:
      db:
        condition: service_healthy
      presence-db:
        condition: service_healthy
      storage:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-app}@db:5432/app
      - PRESENCE_DB_URL=redis://presence-db:6379
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD:-minioadmin}
    secrets:
      - meshy_api_key
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"

  db:
    container_name: db-dev
    image: postgres:18
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    volumes:
      - db_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 1s
      timeout: 5s
      retries: 10
  
  storage:
    container_name: storage-dev
    image: ft_transcendence:minio
    build:
      context: ./submodules/minio
      dockerfile: ../../Dockerfile.minio
    command: server /data --console-address :9001
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - storage_data:/data
  
  presence-db:
    container_name: redis-dev
    image: redis:8.4
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "ping"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "6379:6379"

volumes:
  db_data:
  storage_data:

secrets:
  meshy_api_key:
    file: ./secrets/meshy_api_key.txt
